# MongoDB Configuration
mongodb_root_password: admin123
mongodb_user: devuser
mongodb_pass: admin123
mongodb_db: usersdb
mongodb_port: 30084

# PostgreSQL Configuration
postgres_user: pguser
postgres_pass: pgpass123
postgres_db: devdb
postgres_port: 30074

# Helm Repositories
helm_repo_bitnami: https://charts.bitnami.com/bitnami
helm_repo_prometheus: https://prometheus-community.github.io/helm-charts
