- name: K3s & Helm Initialization
  hosts: localhost
  become: true
  tags: [init]

  tasks:
    - name: Check if K3s is already installed
      stat:
        path: /usr/local/bin/k3s
      register: k3s_installed

    - name: Install K3s if not present
      shell: |
        curl -sfL https://get.k3s.io | sh -
      when: not k3s_installed.stat.exists

    - name: Copy K3s kubeconfig to ~/.kube/config
      shell: |
        mkdir -p ~/.kube
        cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
        chown $USER: ~/.kube/config
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Install Helm if not present
      stat:
        path: /usr/local/bin/helm
      register: helm_installed

    - name: Download and install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      when: not helm_installed.stat.exists

    - name: Add Bitnami Helm repo
      shell: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Update Helm repos
      shell: helm repo update

- name: Install Mongo, PostgreSQL and Prometheus
  hosts: localhost
  become: true
  tags: [init-dbs]

  tasks:

  - name: Check if MongoDB is already installed
    shell: helm list -q | grep -w mongodb
    register: mongodb_installed
    failed_when: false
    changed_when: false

  - name: Install MongoDB via Helm
    when: mongodb_installed.stdout == ""
    shell: |
      helm install mongodb bitnami/mongodb \
        --set auth.rootPassword={{ mongodb_root_password }} \
        --set auth.username={{ mongodb_user }} \
        --set auth.password={{ mongodb_pass }} \
        --set auth.database={{ mongodb_db }} \
        --set service.type=NodePort \
        --set service.nodePorts.mongodb={{ mongodb_port }}

  - name: Check if PostgreSQL is already installed
    shell: helm list -q | grep -w postgresql
    register: postgresql_installed
    failed_when: false
    changed_when: false

  - name: Install PostgreSQL via Helm
    when: postgresql_installed.stdout == ""
    shell: |
      helm install postgresql bitnami/postgresql \
        --set auth.postgresPassword={{ postgres_pass }} \
        --set auth.username={{ postgres_user }} \
        --set auth.password={{ postgres_pass }} \
        --set auth.database={{ postgres_db }} \
        --set service.type=NodePort \
        --set service.nodePort={{ postgres_port }}
  
  - name: Add Prometheus Helm repo
    shell: helm repo add prometheus-community {{ helm_repo_prometheus }}
  
  - name: Install Prometheus via Helm
    shell: |
      helm install prometheus prometheus-community/prometheus
  

- name: Clean K3s Cluster
  hosts: localhost
  become: true
  tags: [clean]

  tasks:

    - name: Uninstall Helm releases
      shell: |
        helm uninstall mongodb || true
        helm uninstall postgresql || true
        helm uninstall pgadmin4 || true
        helm uninstall mongo-express || true
        helm uninstall prometheus || true

    - name: Delete all Kubernetes resources (optional)
      shell: |
        kubectl delete all --all --force --grace-period=0

    - name: Reset K3s cluster (optional, dangerous)
      shell: |
        /usr/local/bin/k3s-uninstall.sh
      when: reset_k3s | default(false)



